server:
  ssl:
    key-store: /ssl/metaphorce/localhost.p12
    key-store-password: JR1L0aX0
    key-store-type: pkcs12
    key-password: JR1L0aX0
  port: 8082
spring:
  application:
    name: MetaphorceService
  datasource:
    url: jdbc:postgresql://192.168.3.40:5432/spring
    username: spring
    password: s3cr3t
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.3.40:9091/realms/metaphorce
          jwk-set-uri: http://192.168.3.40:9091/realms/metaphorce/protocol/openid-connect/certs
      client:
        registration:
          keycloack:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloack:
            issuer-uri: http://192.168.3.40:9091/realms/metaphorce
            user-name-attribute: preferred_username
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    hostName: 192.168.3.40
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.instance.hostName}:${server.port}/actuator/info'
    healthCheckUrl: 'https://${eureka.instance.hostName}:${server.port}/actuator/health'
    homePageUrl: 'https://${eureka.instance.hostName}:${server.port}/'
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone : http://192.168.3.40:8761/eureka/
logging:
  level:
    org:
      springframework:
        security: INFO