server:
  ssl:
    key-store: /ssl/metaphorce/localhost.p12
    key-store-password: JR1L0aX0
    key-store-type: pkcs12
    key-password: JR1L0aX0
  port: 8090
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
        default-filters: TokenRelay
        routes:
        - id: METAPHORCESERVICE
          uri: lb://METAPHORCESERVICE
          predicates:
          - Path=/api/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.3.40:9091/realms/metaphorce
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    hostName: 192.168.3.40
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.instance.hostName}:${server.port}/actuator/info'
    healthCheckUrl: 'https://${eureka.instance.hostName}:${server.port}/actuator/health'
    homePageUrl: 'https://${eureka.instance.hostName}:${server.port}/'
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone : http://192.168.3.40:8761/eureka/
logging:
  level:
    org:
      springframework:
        security: INFO