scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: true
    scheme: http
    scrape_interval: 5s
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets: ['192.168.3.40:8082' , '192.168.3.40:8090', '192.168.3.40:8761']
  - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.3.40:8080']
  - job_name: 'node-exporter'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.3.40:9100']
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.3.40:9093"